name: Coverage Badge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get Coverage
        shell: bash
        run: |
          npm run test:coverage
          COV=$(node -p 't=require(`./coverage/coverage-summary.json`).total,Math.min(...`lines|statements|functions|branches`.split(`|`).map(k=>t[k].pct))')
          echo "coverage=$COV" >> $GITHUB_OUTPUT

      - name: Create Badge
        shell: bash
        run: |
          npm i -g badgen-cli
          export COV=${{ steps.get-values.outputs.coverage }}
          badgen -j coverage --status $COV% --flat --color 4CEB9C > assets/coverage.svg

      - name: Deploy Badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ci: Update badges [skip ci]'
          skip_fetch: true
          skip_checkout: true
